FRUK-Simulator/Simulator

- package-lock.json
- package.json
I made it an exact version and not `^1.0.0` because there's a good chance we might not follow sem versioning in the beginning stages. I think we should use exact versions until things are stable and we really are just publishing minor and patches with guaranteed no breaking changes (or bugs :))
> install simulator-core from npm

- src/BlocklyInterface/robotblocks/constants/ConstantsSection.ts
- src/BlocklyInterface/robotblocks/general/GeneralBlocks.js
- src/BlocklyInterface/robotblocks/general/GeneralSection.tsx
- src/BlocklyInterface/robotblocks/logic/LogicSection.ts
- src/BlocklyInterface/robotblocks/loops/LoopSection.ts
- src/BlocklyInterface/robotblocks/math/MathSection.ts
- src/BlocklyInterface/toolbox.ts
After spending some time in the FTC blockly implementation, it's becoming clear to me that their blocks won't be importable directly on their own. There's a significant amount of hard-coded calls to Blockly.FtcJava (their Blockly generator), as well as some transpilation from other sources.
However, the general purpose blocks, those that already exist in Blockly land, can just be imported over as they are, so putting in a little PR to cover that and give us some extra basic non-robot-ey blocks while we have a larger think about what robot specific blocks need to be imported over and how best to do that.
> Add general purpose blocks from FTC blockly implementation

- src/BlocklyInterface/BlocklyEditor.tsx
- src/JavascriptVM/JavascriptVM.css
- src/JavascriptVM/JavascriptVM.tsx
- src/JavascriptVM/VMControls.tsx
- src/JavascriptVM/vm.spec.ts
- src/JavascriptVM/vm.ts
- src/JavascriptVM/vmSlice.ts
Thrown together variable speeds in this PR. Contains just a slow and fast toggle.
One issue i'm not sure what the best solution is for is: when the VM executes in a faster state, the end run of a program through the VM + simulator will end in a different location than in the slower state. If for example you have:
```
Motor(100%);
if (true) {
Motor(0%);
}
```
The presence of the `if(true)` in SLOW will mean that the car in the simulator will be running at 100% speed for an extra like half a second. This means that programs running in fast mode will end at different places to programs running in slow mode. This feels like an issue to me. Anyone have any ideas for what can be done about it?
> Variable speed

- src/BlocklyInterface/BlocklyEditor.tsx
- src/BlocklyInterface/blocklySlice.ts
- src/view/hooks/useProgramDialog.tsx
- src/view/views/MyProgramsView.tsx
- src/view/views/SimulatorView.tsx
Store the `BlocklyInstance` state in redux.  Otherwise any unsaved blockly workspace changes are lost whenever the `BlocklyEditor` tab gets unmounted (e.g. when the user switches to a different tab).
Fixes  #115
> Keep blockly state when switching tabs

- src/JavascriptVM/ChallengeActionsImpl.ts
- src/RobotSimulator/Arenas/base.ts
- src/RobotSimulator/Arenas/lesson1.ts
- src/state/messagesSlice.ts
Arenas/lesson1.ts: Make success/failure messages fade away after a configurable amount of time (default 2s)
Extend the `ChallengeActions` interface so that it provides an option to display messages that fade out after a configurable amount of time.
Related to #122
> Optionally fade out display messages (user notifications)

- src/JavascriptVM/ChallengeActionsImpl.ts
- src/JavascriptVM/JavascriptVM.tsx
- src/RobotSimulator/Arenas/base.ts
- src/RobotSimulator/Arenas/challengeSlice.ts
- src/RobotSimulator/Arenas/lesson1.ts
- src/state/store.ts
- src/view/components/Common/Card.css
- src/view/views/ChallengeView.tsx
- src/view/views/LandingView.tsx
Show the current challenge state in the `LandingView.tsx` and the `ChallengeView` component.
To be able to show the challenge state this commit:
* adds an additional slice, `challengeSlice.ts`, that stores the current state of each challenge.  Challenges can be in one of three states: Pending, Success and Failure.
* Extends the `ChallengeActions` interface to provide lessons an API to mark the current VM run as success/failure.
Closes #114
> Add challenge results display

- src/JavascriptVM/JavascriptVM.tsx
- src/RobotSimulator/Arenas/challengeSlice.ts
- src/view/views/LandingView.tsx
Fix a bug that causes the simulator to loose the challenge state of failed challenges.
The bug can be triggered as follows:
1) Open a challenge (say, challenge A) and produce a failure event
2) Go back to the main menu
3) Re-enter challenge A, and then navigate back to landing page
4) => The status of challenge A has been lost
This commit ensures the challenge slice keeps track of past failures.
Admittedly, the change feels a bit too complicated and there's probably a more elegant
solution to track the challenge status.  I thought about some alternatives, but
all of them would involve even more code changes, which does not seem justified.
I think the most natural way to implement the challenge status tracking is via
the `ChallengeActionsImpl` class.  I.e., if we supply the …
> bug fix: Don't loose challenge failure state

- src/BlocklyInterface/robotblocks/actuators/ActuatorSection.ts
- src/BlocklyInterface/robotblocks/actuators/MotorCombined.ts
This combined block allows atomically setting power to both motors. 
This is needed to allow the robot to predictably move directly forward or backward on slow execution speeds.
Without this the robot would power one side before the other which would cause the robot to list unhelpfully to one side.
Fixes #144
> blockly: add combined motor power set block

- src/JavascriptVM/vm.ts
We should exit from running statements if we are supposed to be waiting.
Without this, a program which ends on a:
wait(n); 
will simply exit before waiting.
Fixes #149
> vm: fix early exit on wait

- src/RobotSimulator/Arenas/lesson1.ts
Relates to https://github.com/FRUK-Simulator/Simulator/issues/153
- Don't emit a 'Robot Wins!' message if the robot has crossed a "bad" zone during the current run.
- Similarly, don't emit a 'Robot Looses!' message if the robot has already reached the 'FinishZoneId' cleanly (i.e. without driving into a bad zone beforehand).
If we are okay with the proposed approach then I can apply this to the other lessons.
> Improve success/failure report messages

- src/core/blockly/programs.ts
Create a new, minimalistic, blockly program that only sets the motor power on one side.  Make this new program the default code that gets loaded on the very first start of the simulator. 
Note that the current logic of handling blockly code (persisting code in local storage across re-loads and challenges etc) remains the same.
Relates to #148 - we can also start with a truly empty blockly editor?  Maybe that's better?  I personally think that showing a minimal, runnable, example is better than no blocks at all, because it provides a more intuitive starting point.  Let me know what you think and I'll update this PR accordingly.
> Show minimal blockly code at the first launch

- src/BlocklyInterface/blocklySlice.ts
- src/state/store.ts
This import was causing a circular dependency since store imports blocklySlice
During the import process, we are not allowed to use any of the values
exported from the modules in the import path.
> remove illegal import from blocklySlice

- src/JavascriptVM/JavascriptVM.tsx
- src/RobotSimulator/robotSimulatorSlice.ts
- src/view/views/RobotView.tsx
the IRobotSpec object wasn't serializable and caused errors to be printed in the console.
This commit instead extracts the relevant information into a new object
and uses that as the payload instead.
> store derived information in state

- src/JavascriptVM/vm.ts
otherwise the delay will be ever present if smaller than the execution interval
fixes #176
> clear remaining delay

- package-lock.json
- package.json
- src/BlocklyInterface/BlocklyEditor.tsx
- src/BlocklyInterface/BlocklyInstance.ts
- src/BlocklyInterface/blocklySlice.ts
- src/JavascriptVM/JavascriptVM.tsx
- src/RobotSimulator/Arenas/base.ts
- src/RobotSimulator/Arenas/lesson1.ts
- src/view/views/BlocklyView.tsx
- src/view/views/SimulatorView.tsx
Fix #92 by allow challange config to specify the number of blocks allowed
to be used. This should help students to identify the are on the wrong
path but it seems like a clear feedback of how many blocks are allowed
is required as blockly simply turn all blocks into "disabled" without
clear explanation why that is.
> Add limit to number of blocks

- src/JavascriptVM/JavascriptVM.tsx
- src/JavascriptVM/vm.ts
This is part of the https://github.com/FRUK-Simulator/Simulator/issues/215
The physical world is not paused when pause button is hit. This PR is to make the arena freeze when paused. When the timer feature is done we can make sure both timer and the arena are paused.
> Pause the simulation when 'Pause' button is clicked

- src/JavascriptVM/JavascriptVM.tsx
- src/RobotSimulator/Arenas/base.ts
- src/RobotSimulator/Arenas/lesson4.ts
- src/RobotSimulator/StdWorldBuilder.ts
Lessons 4 need to have the distance sensor disabled, so we're exposing robot configuration as part of challenge configuration. 
Let me know if we want to tie the robot configuration in with the arena configuration as originally intended, it made more sense to me to make it a separate config.
Closes #244
> Add the ability to configure whether robot has a distance sensor

- package-lock.json
- package.json
- src/JavascriptVM/JavascriptVM.tsx
- src/RobotSimulator/StdWorldBuilder.ts
- src/RobotSimulator/robotSimulatorSlice.ts
- src/view/views/RobotView.tsx
Before this change the information about the motors in RobotView was captured when setting the motors and not from the robot itself.
This now uses the RobotSpec and SimRobot, like the rest of the sensors, to decide what to present and get the actual values of the motors.
https://user-images.githubusercontent.com/187938/205295099-7e4cf85d-6f59-4668-8a54-9b53ebbd34e9.mp4
Depends on https://github.com/FRUK-Simulator/SimulatorCore/pull/194
> Show motors from robot

- .github/workflows/main.yml
Previously, with CRA (Create React App), the build ouputs were put in `build`. Now, with Vite, we changed this to `dist`. Fixing this little error.
> ci: fix artifact generation path in workflow

- .github/workflows/playwright.yml
- .gitignore
- README.md
- package-lock.json
- package.json
- playwright.config.ts
- src/BlocklyInterface/blocklySlice.ts
- tests-examples/demo-todo-app.spec.ts
- tests/example.spec.ts
- vitest.config.ts
This PR:
* Scaffolds [Playwright](https://playwright.dev/) to be used as an end-to-end framework for the project's website.
* Sets up CI for running E2E tests.
* Adds a configuration for *vitest* to explicitly exclude E2E tests.
* Documents different ways of interacting E2E tests.
* Introduce some example tests.
This PR:
* Doesn't write any explicit application E2E tests. This is coming next.
> ci: adding Playwright scaffolding with Readme.md and github actions config

- .releaserc.json
It feels more like spams generating new comment for every single PRs involved in a release. Disabling this behavior based on the docs here: https://github.com/semantic-release/github?tab=readme-ov-file#options
> chore: disable PR comment on release success

- src/AppRoutes.tsx
- src/components/Layout.tsx
- src/index.css
- src/ui/Button.tsx
- src/ui/Typography.tsx
- src/views/Home.tsx
- src/views/Home/Home.tsx
- src/views/Home/shapes-blue.svg
- src/views/Home/shapes-pink.svg
- src/views/Sandbox.tsx
This PR implements home screen.
Goals for this implementation
- Aiming to provide good screen size compatibility for mainstream 4K/5K screens, laptops and tablets
- Aiming to avoid layout crashes for mobile device screen sizes, but mobile screen responsiveness is not in the compatibility list
- The implementation follows the designer's intention to have 2 blocks covering the whole home screen, with appropriate flexible variations for the margin gap between title/subtitle and buttons.
- Color blocks transfer from aligned in row to aligned in column, aiming to provide adequate UX to vertical screen ratios.
**4K large desktop screen W 2560**
**Large laptop W 1440**
**Small laptop/large tablet W 1024**
**iPad Air 1180x820**
A few more extreme sizes
**iPhone 14 Pro Max 430x932**
**iPad air …
> feat: home screen

- .github/workflows/deploy-to-gh-pages.yml
This PR incorporates a deployment to GitHub pages using the [GitHub Deploy Pages action](https://github.com/actions/deploy-pages).
* It builds and deploys the full `./dist` directory, as it is.
* It enables manual triggers of the workflow.
> ci: deploying to GH Pages after push to main
