FRUK-Simulator/Simulator

- package-lock.json
- package.json
- src/App.tsx
- src/ErrorViews/MessageCenter.css
- src/ErrorViews/MessageCenter.tsx
- src/ErrorViews/messagesSlice.ts
- src/JavascriptVM/JavascriptVM.tsx
- src/store.ts
This PR introduces message popups. Not all blockly programs produce valid JS code. In this case, the VM may fail to be initialized if it can't be parsed. This displays an error to the user in such a case and sets up a generic container for all types of errors.
To produce an error, add an actuator with no inputs or other blocks and try to start the program.
> show messages to the user on errors and successes

- package-lock.json
- src/BlocklyInterface/robotblocks/general/GeneralSection.tsx
- src/BlocklyInterface/robotblocks/general/Wait.ts
- src/JavascriptVM/vm.ts
> Added a Blockly wait block

- src/ControlPanel/ControlPanel.tsx
- src/ControlPanel/GameController/GameController.tsx
- src/JavascriptVM/JavascriptVM.tsx
- src/JavascriptVM/VMControls.tsx
- src/RobotSimulator/RobotSimulator.tsx
This hoists up the Sim3D instance into the VM Provider. These two can then more directly interact with each other.
> Move robot simulator state into VM provider

- package-lock.json
- package.json
- src/JavascriptVM/JavascriptVM.tsx
- src/RobotSimulator/Areanas/lesson1.ts
> Program end reset

- src/core/settings/settings.ts
- src/view/components/Common/Icon.css
- src/view/components/Common/Icon.tsx
- src/view/components/Gamepad/GamepadSettings.tsx
- src/view/views/BlocklyView.tsx
- src/view/views/SettingsView.tsx
Follow up to #106 
Persists / loads the settings and changes the icons around to be a little more intuitive.
> persist settings / change icons

- package-lock.json
- package.json
- src/@types/js-interpreter.d.ts
- src/BlocklyInterface/robotblocks/enums/EnumColor.ts
- src/BlocklyInterface/robotblocks/enums/EnumSection.ts
- src/BlocklyInterface/robotblocks/sensors/SensorColor.ts
- src/BlocklyInterface/robotblocks/sensors/SensorSection.ts
- src/BlocklyInterface/toolbox.ts
- src/JavascriptVM/JavascriptVM.tsx
- src/JavascriptVM/vm.ts
Fixes #79
Note that this requires the a fix in SimulatorCore to build which is PR'd in https://github.com/FRUK-Simulator/SimulatorCore/pull/124
It also requires a further fix (as yet undiscovered) for the color sensor in SimulatorCore to actually return a value.
> Add color sensor

- src/JavascriptVM/JavascriptVM.tsx
- src/JavascriptVM/vm.ts
- src/JavascriptVM/vmSlice.ts
- src/core/settings/settings.ts
- src/view/views/SettingsView.tsx
Extend the setting view, so that the user can control the camera mode.
Closes #105
> Add view options (Top Down, follow the robot ...)

- src/JavascriptVM/JavascriptVM.tsx
- src/view/views/SettingsView.tsx
This is only intended for debugging the simulator.
> add debug mode to show state of physics world

- src/JavascriptVM/JavascriptVM.tsx
- src/RobotSimulator/StdWorldBuilder.ts
- src/RobotSimulator/robotSimulatorSlice.ts
- src/view/components/Common/StatusTile.css
- src/view/components/Common/StatusTile.tsx
- src/view/views/RobotView.tsx
Currently the robot view tab only shows the motors of the robot. This PR extends the tab to include the various robot sensors (distance, contact, color).
> RobotView: Show robot sensors

- src/view/components/SaveProgramButton/SaveProgramButton.tsx
- src/view/views/BlocklyView.tsx
- src/view/views/RobotView.tsx
> RobotView: Show VM and editor controls

- .gitignore
- README.md
Add details about how to setup `.npmrc` to use the public npm registry.
Add gitignore to `.npmrc` file so people who do use it won't commit it.
> Add details about `.npmrc` to README

- src/RobotSimulator/Arenas/lesson4.ts
- src/RobotSimulator/ChallengeConfigLoader.ts
Implement issue #193.
Please see Lesson 4 Challange B and notice the z-fighting of define 2 zones one on top of the other.
> wip - very initial draft of challenge 4

- src/view/components/Header/Header.css
- src/view/components/Header/Header.tsx
resolves https://github.com/FRUK-Simulator/Simulator/issues/201
> add feedback button

- src/view/components/Common/Form.tsx
- src/view/components/Common/MarkdownDisplay.tsx
- src/view/views/RobotView.tsx
resolves https://github.com/FRUK-Simulator/Simulator/issues/206
> Fix console warnings

- src/view/components/MessageCenter/MessageCenter.css
fixes https://github.com/FRUK-Simulator/Simulator/issues/122
> move toasts to bottom right of ui

- package-lock.json
- package.json
- src/RobotSimulator/Arenas/lesson4.ts
https://github.com/FRUK-Simulator/Simulator/issues/204
Lesson 4 Should have walls which the distance sensor can detect and help the robot navigate the arena, they are curently represented by zones, however they need to be extra walls defined in the arena definition.
Depends on the PR to **SimulatorCore** https://github.com/FRUK-Simulator/SimulatorCore/pull/169
Walls are added to the map:
> Convert bad areas to walls

- package-lock.json
- package.json
- src/view/components/Common/StatusTile.css
- src/view/components/Common/StatusTile.tsx
- src/view/views/RobotView.tsx
Closes #90 
Displays the current detected color by the color sensor in the Robot tab - if no color has been detected we will display white.
> Fix color sensor display in Robot view

- src/view/components/Common/StatusTile.css
- src/view/components/Common/StatusTile.tsx
- src/view/views/RobotView.tsx
Show the actual color as color block and as an RGB hex value.
> Update color sensor display

- src/view/components/Header/Header.tsx
- src/view/components/Header/timer.tsx
Related to this #192 
Currently the timer stops when Robots stops. 
Next steps:
In a another PR will address that it should stop when it wins/fails even if robot continued execution + show the success completion time on each challenge
> Introduces Timer functionality

- src/view/components/Header/Header.css
- src/view/components/Header/Header.tsx
- src/view/components/Header/timer.tsx
Closes https://github.com/FRUK-Simulator/Simulator/issues/239
> update timer styling

- package.json
- src/RobotSimulator/Arenas/lesson5.ts
- src/RobotSimulator/ChallengeConfigLoader.ts
https://github.com/FRUK-Simulator/Simulator/issues/227
A starting point for lesson 5. The lesson/challenge description might not be accurate. The event handler is not fully tested so far. This PR is for setting up the layout.
> add lesson 5 challenge A

- src/BlocklyInterface/BlocklyInstance.ts
> fix functions

- src/Components/README.md
This PR adds a README file to the Components folder, for listing the UI components that are / to be made available as part of completing this Web application.
It is based on an audit of the Design System (and focusing on Page 2).
> docs: add a README for listing UI components
